# Font settings
font_family Caskaydia Cove Nerd Font
font_size 20.0
disable_ligatures never

# Zooming
map ctrl+equal change_font_size all +2.0
map ctrl+minus change_font_size all -2.0
map ctrl+backspace change_font_size all 0

# Theme
include gruvbox-dark.conf
